mybatis:
  mapper-locations: classpath:*.xml
  type-aliases-package: com.xlinclass
server:
  port: 8088
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/xlinclasswx-dev?useUnicode=true&characterEncoding=utf-8
    username: root
    type: com.zaxxer.hikari.HikariDataSource