
server:
  port: 8099
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/xlinclasswx-dev?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    type: com.zaxxer.hikari.HikariDataSource
mybatis:
  type-aliases-package: com.xlinclass
  mapper-locations: classpath:*.xml